a=int(input("Enter data:"))
print("Your datatype is:",type(a))
b=float(input("Enter data:"))
print("Your datatype is:",type(b))
c=dict(input("Enter data:"))
print("Your datatype is:",type(c))
d=tuple(input("Enter data:"))
print("Your datatype is:",type(d))
e=str(input("Enter data:"))
print("Your datatype is:",type(e))
f=set(input("Enter data:"))
print("Your datatype is:",type(f))
